com:
  hhao:
    metadata:
      enabled: true
      # 配置与日期时间格式化相关
      formatters:
        dateTime: "yyyy-MM-dd HH:mm:ss"
        date: "yyyy-MM-dd"
        time: "HH:mm:ss"
      timezone: "UTC+8"
      locale: "zh-CN"
      versionInfo: "::1.1.1-SNAPSHOT"
      monetaryConfig:
        defaultCurrency: "CNY"
        patternPlaceSymbol: "¤"
        currencyConfigurations:
          CNY:
            currencyCode: "CNY"
            locale: "zh-CN"
            displayPattern: "SYMBOL:¤#,###0.00"
            parsePattern: "CODE:¤#,###0.00"
            precision: 16
            scale: 2
            roundingMode: HALF_EVEN
            fixedScale: true
          USD:
            currencyCode: "USD"
            locale: "en-US"
            displayPattern: "SYMBOL:¤#,###0.00"
            parsePattern: "CODE:¤#,###0.00"
            precision: 16
            scale: 2
            roundingMode: HALF_EVEN
            fixedScale: true
